// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Mp3Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Mp3Player_h__
#define __Mp3Player_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Mp3Player
{

class Manage;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Mp3Player::Manage>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Mp3Player::Manage*);

}

}

namespace Mp3Player
{

class Manage;
bool operator==(const Manage&, const Manage&);
bool operator<(const Manage&, const Manage&);
::Ice::Object* upCast(::Mp3Player::Manage*);
typedef ::IceInternal::Handle< ::Mp3Player::Manage> ManagePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Mp3Player::Manage> ManagePrx;
void __patch(ManagePtr&, const ::Ice::ObjectPtr&);

}

namespace Mp3Player
{

typedef ::std::vector< ::Ice::Byte> byteArray;

typedef ::std::vector< ::std::string> stringArray;

}

namespace Mp3Player
{

class Callback_Manage_addFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Manage_addFile_Base> Callback_Manage_addFilePtr;

class Callback_Manage_removeFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Manage_removeFile_Base> Callback_Manage_removeFilePtr;

class Callback_Manage_getFilesList_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Manage_getFilesList_Base> Callback_Manage_getFilesListPtr;

class Callback_Manage_findByName_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Manage_findByName_Base> Callback_Manage_findByNamePtr;

}

namespace IceProxy
{

namespace Mp3Player
{

class Manage : virtual public ::IceProxy::Ice::Object
{
public:

    void addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size)
    {
        addFile(name, offset, bytes, size, 0);
    }
    void addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx)
    {
        addFile(name, offset, bytes, size, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addFile(name, offset, bytes, size, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addFile(name, offset, bytes, size, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addFile(name, offset, bytes, size, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addFile(name, offset, bytes, size, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size)
    {
        return begin_addFile(name, offset, bytes, size, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx)
    {
        return begin_addFile(name, offset, bytes, size, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(name, offset, bytes, size, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(name, offset, bytes, size, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Mp3Player::Callback_Manage_addFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(name, offset, bytes, size, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::std::string& name, ::Ice::Int offset, const ::Mp3Player::byteArray& bytes, ::Ice::Int size, const ::Ice::Context& __ctx, const ::Mp3Player::Callback_Manage_addFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(name, offset, bytes, size, &__ctx, __del, __cookie);
    }

    void end_addFile(const ::Ice::AsyncResultPtr&);
    
private:

    void addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void removeFile(const ::std::string& name)
    {
        removeFile(name, 0);
    }
    void removeFile(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        removeFile(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_removeFile(const ::std::string& name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_removeFile(name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_removeFile(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_removeFile(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_removeFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_removeFile(name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_removeFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_removeFile(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name)
    {
        return begin_removeFile(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_removeFile(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFile(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFile(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name, const ::Mp3Player::Callback_Manage_removeFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFile(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::Mp3Player::Callback_Manage_removeFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFile(name, &__ctx, __del, __cookie);
    }

    void end_removeFile(const ::Ice::AsyncResultPtr&);
    
private:

    void removeFile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_removeFile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Mp3Player::stringArray getFilesList()
    {
        return getFilesList(0);
    }
    ::Mp3Player::stringArray getFilesList(const ::Ice::Context& __ctx)
    {
        return getFilesList(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getFilesList(const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFilesList(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesList(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFilesList(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesList(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFilesList(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesList(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFilesList(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getFilesList(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Mp3Player::stringArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
                ::Mp3Player::stringArray __ret;
                try
                {
                    __ret = __proxy->end_getFilesList(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Mp3Player::stringArray&)> _response;
        };
        return begin_getFilesList(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getFilesList()
    {
        return begin_getFilesList(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFilesList(const ::Ice::Context& __ctx)
    {
        return begin_getFilesList(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFilesList(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesList(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesList(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesList(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesList(const ::Mp3Player::Callback_Manage_getFilesListPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesList(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesList(const ::Ice::Context& __ctx, const ::Mp3Player::Callback_Manage_getFilesListPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesList(&__ctx, __del, __cookie);
    }

    ::Mp3Player::stringArray end_getFilesList(const ::Ice::AsyncResultPtr&);
    
private:

    ::Mp3Player::stringArray getFilesList(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getFilesList(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Mp3Player::stringArray findByName(const ::std::string& name)
    {
        return findByName(name, 0);
    }
    ::Mp3Player::stringArray findByName(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return findByName(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findByName(const ::std::string& name, const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findByName(name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findByName(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findByName(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findByName(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findByName(name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findByName(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findByName(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findByName(const ::std::string& name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Mp3Player::stringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Mp3Player::stringArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
                ::Mp3Player::stringArray __ret;
                try
                {
                    __ret = __proxy->end_findByName(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Mp3Player::stringArray&)> _response;
        };
        return begin_findByName(name, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name)
    {
        return begin_findByName(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_findByName(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findByName(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findByName(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name, const ::Mp3Player::Callback_Manage_findByNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findByName(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findByName(const ::std::string& name, const ::Ice::Context& __ctx, const ::Mp3Player::Callback_Manage_findByNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findByName(name, &__ctx, __del, __cookie);
    }

    ::Mp3Player::stringArray end_findByName(const ::Ice::AsyncResultPtr&);
    
private:

    ::Mp3Player::stringArray findByName(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findByName(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Manage> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_secure(bool __secure) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_twoway() const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_oneway() const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_batchOneway() const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_datagram() const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_batchDatagram() const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_compress(bool __compress) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Manage> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Manage*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Mp3Player
{

class Manage : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void removeFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Mp3Player::stringArray getFilesList(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Mp3Player::stringArray findByName(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Mp3Player
{

class Manage : virtual public ::IceDelegate::Mp3Player::Manage,
               virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void removeFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Mp3Player::stringArray getFilesList(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Mp3Player::stringArray findByName(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Mp3Player
{

class Manage : virtual public ::IceDelegate::Mp3Player::Manage,
               virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void removeFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Mp3Player::stringArray getFilesList(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Mp3Player::stringArray findByName(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Mp3Player
{

class Manage : virtual public ::Ice::Object
{
public:

    typedef ManagePrx ProxyType;
    typedef ManagePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void addFile(const ::std::string&, ::Ice::Int, const ::Mp3Player::byteArray&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void removeFile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___removeFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Mp3Player::stringArray getFilesList(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getFilesList(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Mp3Player::stringArray findByName(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___findByName(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Manage& l, const Manage& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Manage& l, const Manage& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Mp3Player
{

template<class T>
class CallbackNC_Manage_addFile : public Callback_Manage_addFile_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Manage_addFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Manage_addFilePtr
newCallback_Manage_addFile(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_addFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_addFilePtr
newCallback_Manage_addFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_addFile<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Manage_addFilePtr
newCallback_Manage_addFile(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_addFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_addFilePtr
newCallback_Manage_addFile(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_addFile<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Manage_addFile : public Callback_Manage_addFile_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Manage_addFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Manage_addFilePtr
newCallback_Manage_addFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_addFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_addFilePtr
newCallback_Manage_addFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_addFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_addFilePtr
newCallback_Manage_addFile(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_addFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_addFilePtr
newCallback_Manage_addFile(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_addFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Manage_removeFile : public Callback_Manage_removeFile_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Manage_removeFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_removeFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_removeFile<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_removeFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_removeFile<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Manage_removeFile : public Callback_Manage_removeFile_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Manage_removeFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_removeFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_removeFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_removeFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_removeFilePtr
newCallback_Manage_removeFile(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_removeFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Manage_getFilesList : public Callback_Manage_getFilesList_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Mp3Player::stringArray&);

    CallbackNC_Manage_getFilesList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
        ::Mp3Player::stringArray __ret;
        try
        {
            __ret = __proxy->end_getFilesList(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Manage_getFilesListPtr
newCallback_Manage_getFilesList(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Mp3Player::stringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_getFilesList<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_getFilesListPtr
newCallback_Manage_getFilesList(T* instance, void (T::*cb)(const ::Mp3Player::stringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_getFilesList<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Manage_getFilesList : public Callback_Manage_getFilesList_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Mp3Player::stringArray&, const CT&);

    Callback_Manage_getFilesList(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
        ::Mp3Player::stringArray __ret;
        try
        {
            __ret = __proxy->end_getFilesList(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Manage_getFilesListPtr
newCallback_Manage_getFilesList(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Mp3Player::stringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_getFilesList<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_getFilesListPtr
newCallback_Manage_getFilesList(T* instance, void (T::*cb)(const ::Mp3Player::stringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_getFilesList<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Manage_findByName : public Callback_Manage_findByName_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Mp3Player::stringArray&);

    CallbackNC_Manage_findByName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
        ::Mp3Player::stringArray __ret;
        try
        {
            __ret = __proxy->end_findByName(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Manage_findByNamePtr
newCallback_Manage_findByName(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Mp3Player::stringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_findByName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Manage_findByNamePtr
newCallback_Manage_findByName(T* instance, void (T::*cb)(const ::Mp3Player::stringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Manage_findByName<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Manage_findByName : public Callback_Manage_findByName_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Mp3Player::stringArray&, const CT&);

    Callback_Manage_findByName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Mp3Player::ManagePrx __proxy = ::Mp3Player::ManagePrx::uncheckedCast(__result->getProxy());
        ::Mp3Player::stringArray __ret;
        try
        {
            __ret = __proxy->end_findByName(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Manage_findByNamePtr
newCallback_Manage_findByName(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Mp3Player::stringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_findByName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Manage_findByNamePtr
newCallback_Manage_findByName(T* instance, void (T::*cb)(const ::Mp3Player::stringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Manage_findByName<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
