// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Mp3Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mp3Player;

public abstract class Callback_Manage_removeFile extends Ice.OnewayCallback
{
}
